# HTTP Server
server:
  port: 16346  # HTTP (Tomcat) port

spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDRS:nacos:8848}
  application:
    name: ts-travel2-service
  datasource:
    url: jdbc:mysql://${TRAVEL2_MYSQL_HOST:ts}:${TRAVEL2_MYSQL_PORT:3306}/${TRAVEL2_MYSQL_DATABASE:travel2}?useSSL=false
    username: ${TRAVEL2_MYSQL_USER:root}
    password: ${TRAVEL2_MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
swagger:
  controllerPackage: travel2.controller
