server:
  port: 18767

spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDRS:nacos:8848}
  application:
    name: ts-admin-basic-info-service

swagger:
  controllerPackage: adminbasic.microservice
