server:
  port: 18898

spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDRS:nacos:8848}
  application:
    name: ts-seat-service

swagger:
  controllerPackage: seat.controller
