# HTTP Server
server:
  port: 17525  # HTTP (Tomcat) port

spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDRS:nacos:8848}
  application:
    name: ts-wait-order-service
  datasource:
    url: jdbc:mysql://${WAIT_ORDER_MYSQL_HOST:ts}:${WAIT_ORDER_MYSQL_PORT:3306}/${WAIT_ORDER_MYSQL_DATABASE:waitOrder}?useSSL=false
    username: ${WAIT_ORDER_MYSQL_USER:root}
    password: ${WAIT_ORDER_MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

swagger:
  controllerPackage: waitorder.controller