# HTTP Server
server:
  port: 14322  # HTTP (Tomcat) port

spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDRS:nacos:8848}
  application:
    name: ts-travel-plan-service


swagger:
  controllerPackage: travelplan.controller
