server:
  port: 16112

spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDRS:nacos:8848}
  application:
    name: ts-admin-order-service


swagger:
  controllerPackage: adminorder.controller


